# Prerequisito: https://docs.docker.com/compose/install/
# Encender la máquina: docker-compose up -d
# Apagar la máquina:   docker-compose down
version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    image: 'sg'
    restart: always
    env_file:
      - .env
    ports:
      - 8070:80
    volumes:
      - ./:/var/www/html
    tty: true
    stdin_open: true


